Approvals webhook notification
Jexactyl/Jexactyl pull request #103
Opened 2022-08-17 08:22 UTC by TheFallenSpirit

This pr adds a webhook notification when a user creates an account if approvals are enabled.

2022-08-21 10:05 UTC, Shersha01 approved these changes
should have this added

2022-08-26 13:48 UTC, cmrxnn requested changes
Please review my comments.

2022-08-26 13:48 UTC, cmrxnn commented on app/Http/Controllers/Admin/Jexactyl/ApprovalsController.php
> +            'webhook' => $this->settings->get('jexactyl::approvals:webhook', false),
Remove the `false` fallback value. If there isn't anything, it'll just show up as empty anyway. (For the webhook_url)

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +        if ($this->settings->get('jexactyl::approvals:webhook') === 'true' && strlen($this->settings->get('jexactyl::approvals:webhook_url')) > 0) {
No need for this strlen expression. Just ensure that `webhook_url` returns a value.

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +                        'footer' => ['text' => 'Jexactyl', 'icon_url' => 'https://avatars.githubusercontent.com/u/91636558'],
Instead of this being 'Jexactyl', use $name.

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +                'username' => 'Jexactyl',
Instead of this being 'Jexactyl', use $name.

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +                        'description' => 'A new user account has been created on ' . $name,
Just leave this as: 'A new account has been created!'

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +                        'color' => 11821768,
Ensure this is the same hex code as the current Jexactyl logo.

2022-08-26 13:48 UTC, cmrxnn commented on app/Services/Users/UserCreationService.php
> +            Http::withBody(json_encode($webhook_data), 'application/json')->post($this->settings->get('jexactyl::approvals:webhook_url'));
Add a try/catch statement here.

2022-08-26 13:48 UTC, cmrxnn commented on public/themes/jexactyl/css/jexactyl.css
> +}
What is the need for these?

2022-08-26 13:48 UTC, cmrxnn commented on resources/views/admin/jexactyl/approvals.blade.php
> +                                <p class="text-muted"><small>Enable this to send a Discord Webhook when a user registers.</small></p>
Replace this with 'Provide the Webhook URL to use when a user needs to be approved.'

2022-08-27 20:41 UTC, TheFallenSpirit commented
Will be reopened once I re-add the code.

2022-08-28 04:16 UTC, Shersha01 approved these changes

2022-09-02 23:03 UTC, cmrxnn approved these changes
LGTM

2022-09-02 23:04 UTC, merged