few improvements
Jexactyl/Jexactyl pull request #15
Opened 2022-06-18 18:00 UTC by OlekAleksander

2022-06-18 18:04 UTC, cmrxnn commented
As far as I can see, the admin area improvement does not include the link to the Discord.

2022-06-18 18:07 UTC, OlekAleksander commented
sorry i forgot, fixing

2022-06-18 18:13 UTC, OlekAleksander commented
is it better now?

2022-06-19 11:46 UTC, cmrxnn requested changes
Waiting for changes to be made as per my comnments.

2022-06-19 11:46 UTC, camwhi-te commented on resources/scripts/components/dashboard/activity/ActivityLogContainer.tsx
> +            <h3 css={tw`text-2xl text-neutral-500`}>View your recent Activity</h3>
Would be better to change this to:

Account Activity
View your recent activity.

2022-06-19 11:46 UTC, camwhi-te commented on resources/views/admin/index.blade.php
> +    <div class="col-xs-6 col-sm-3 text-center"><a href="https://discord.gg/ECYh2DFNkF"><button class="btn btn-warning" style="width:100%;"><i class="fa fa-fw fa-support"></i> Discord </button></a>
Please set this link to: https://discord.gg/qttGR4Z5Pk

2022-06-19 20:52 UTC, OlekAleksander commented
Done

2022-06-20 14:32 UTC, merged